# Generated by Django 5.0.6 on 2024-06-04 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentReport', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studens',
            options={},
        ),
    ]
