# Generated by Django 5.0.6 on 2024-06-04 22:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentReport', '0002_alter_studens_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studens',
            name='lessonScore',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)]),
        ),
    ]
